In [121]:
import numpy as np
from scipy.linalg import solve

# Scalar:

In [9]:
x = np.array(30)

In [10]:
print(x)

30


# The conventional explanation goes, x is a magnitude with no direction

In [13]:
x = np.array([10,20,40,66,77,49])

In [14]:
print(x)

[10 20 40 66 77 49]


In [15]:
print(x.T)

[10 20 40 66 77 49]


# Above didn't transpose because x is one-dimensional

Source : https://stackoverflow.com/questions/5954603/transposing-a-numpy-array

In [17]:
x= np.array([[10,20,40,66,77,49]])

In [18]:
print(x)

[[10 20 40 66 77 49]]


In [19]:
print(x.T)

[[10]
 [20]
 [40]
 [66]
 [77]
 [49]]


# Now there's a transpose of x coz it's 2D

# Here's a neat trick:

In [20]:
x = np.array([10,20,40,66,77,49])

In [21]:
print(x)

[10 20 40 66 77 49]


In [22]:
x.reshape(-1,1)

array([[10],
       [20],
       [40],
       [66],
       [77],
       [49]])

In [25]:
x[0]

10

In [26]:
x[[0,0]]

array([10, 10])

In [27]:
x[[0,1]]

array([10, 20])

# Using indices:

In [34]:
x[[1,3,5]]

array([20, 66, 49])

# Matrices, aka 2D arrays:

In [53]:
x = np.array([[1,2],[3,4]])

In [54]:
print(x)

[[1 2]
 [3 4]]


In [55]:
x= np.array([[1,2,3,4],[5,6,7,8]])

In [56]:
print(x)

[[1 2 3 4]
 [5 6 7 8]]


# this works too, for some reason:

In [57]:
x = np.array([[1,2,3],[4,5,6,7]])

In [58]:
print(x)

[list([1, 2, 3]) list([4, 5, 6, 7])]


# Tensors, aka multi-D arrays:

In [59]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [60]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
x.shape

(3, 3)

# If we dont declare x as an np.array, the .shape attribute wont work.

# Transpose of a matrix:

In [63]:
x = np.array([[1,2],[3,4]])

In [64]:
print(x)

[[1 2]
 [3 4]]


In [65]:
print(x.T)

[[1 3]
 [2 4]]


In [67]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [68]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
print(x.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [71]:
x = np.array([[1,2,3],[4,5,6]])

In [72]:
print(x)

[[1 2 3]
 [4 5 6]]


In [73]:
print(x.T)

[[1 4]
 [2 5]
 [3 6]]


# Broadcasting:

In [74]:
x = np.array([[1],[2],[3]])

In [75]:
c = 1

In [76]:
print(x)

[[1]
 [2]
 [3]]


In [77]:
print(c)

1


In [78]:
b = x + c

In [79]:
print(b)

[[2]
 [3]
 [4]]


# Even though c wasn't explicitly defined as a vector, the addition operation worked out like we would have expected it to work out

# This implicit copying of lower - D scalars / vectors is called broadcasting

# Multiplying matrics and vectors:

In [80]:
x = np.array([[1,2,3],[4,5,6]])

In [81]:
print(x)

[[1 2 3]
 [4 5 6]]


In [82]:
x.shape

(2, 3)

In [83]:
y = np.array([[1,2],[3,4],[5,6]])

In [84]:
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [85]:
y.shape

(3, 2)

In [86]:
z = x * y

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Source : https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

In [87]:
z = numpy.dot(x,y)

In [88]:
print(z)

[[22 28]
 [49 64]]


In [89]:
z.shape

(2, 2)

In [90]:
z = x @ y

In [91]:
print(z)

[[22 28]
 [49 64]]


In [93]:
z.shape

(2, 2)

# The above is the matrix product, if we just want the elementwise product, then:

Source : https://stackoverflow.com/questions/40034993/how-to-get-element-wise-matrix-multiplication-hadamard-product-in-numpy

### Note:
a * b - elementwise multiplication<br>
a @ b - matrix multiplication

In [94]:
x * y

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [99]:
x = np.array([[1,2],[3,4]])

In [100]:
print(x)

[[1 2]
 [3 4]]


In [97]:
y = np.array([[5,6],[7,8]])

In [101]:
print(y)

[[5 6]
 [7 8]]


### Elementwise multiplication a.k.a Hadamard product:

In [98]:
x * y

array([[ 5, 12],
       [21, 32]])

### Matrix multiplication:

In [102]:
x @ y

array([[19, 22],
       [43, 50]])

# The dot product of 2 vectors, x and y is , the transpose of x multiplied by y.

dot product = x<sup>T</sup>y

In [105]:
dot_prod = x.T @ y

In [106]:
print(dot_prod)

[[26 30]
 [38 44]]


# Tbh, we should know this, but it's been a while.....So, here we go:

### Is dot product the same as the matrix product?

In [108]:
x = np.array([[1,2],[3,4]])

In [110]:
print(x)

[[1 2]
 [3 4]]


In [109]:
y = np.array([[5,6],[7,8]])

In [111]:
print(y)

[[5 6]
 [7 8]]


### Matrix product:

In [112]:
x @ y

array([[19, 22],
       [43, 50]])

### Dot product:

In [116]:
x.T * y

array([[ 5, 18],
       [14, 32]])

In [115]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

# As you can see the matrix product, itself is defined by the np.dot() function. This has thoroughly confused me. What is the x.T * y above then?

Source: https://math.stackexchange.com/questions/2354047/dot-product-versus-matrix-multiplication-is-the-later-a-special-case-of-the-fir

# The above post makes some sense, the matrix product is only for matrices, whereas the dot product can be defined for any 2 vectors, and is a form of the vector product between vectors, the other being the cross product

## ****Maybe we can talk to someone and gain some clarity on the above.****

# Solving equations with matrices and variables:

Ax = b

In [134]:
# A = np.array([[1,2],[3,4]])

In [120]:
print(A)

[[1 2]
 [3 4]]


In [123]:
A = np.random(3,3)

TypeError: 'module' object is not callable

In [124]:
A = np.random((3,3))

TypeError: 'module' object is not callable

In [125]:
A = np.random.random(3,3)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [126]:
A = np.random.random((3,3))

In [127]:
print(A)

[[0.46321872 0.30546451 0.13043122]
 [0.47730703 0.77610127 0.70787207]
 [0.08014092 0.55467713 0.50004967]]


In [129]:
b = np.random.random(3)

In [130]:
print(b)

[0.95420557 0.64038064 0.01714017]


In [131]:
x = solve(A,b)

In [132]:
print(x)

[ 1.72250759  1.16829563 -1.53770733]


In [133]:
np.dot(A,x) - b

array([-2.22044605e-16, -1.11022302e-16,  0.00000000e+00])

Source: https://stackoverflow.com/questions/22163113/matrix-multiplication-solve-ax-b-solve-for-x

## The e-16 is small enough to be read as 0.

# Alternative: (Personally found this more intuitive mathematically, though solve is simple enough)

# Ax = b
# x = A<sup>-1</sup>b

In [141]:
A = np.random.random((3,3))

In [142]:
b = np.random.random(3)

In [143]:
x= np.dot(np.linalg.inv(A),b)

In [144]:
x

array([ 22.08355682,  -0.690773  , -18.26214412])

In [145]:
np.dot(A,x) - b

array([1.11022302e-15, 1.77635684e-15, 2.66453526e-15])

## e-15 is small enough to be read as 0.

# Identity and Inverse Matrices:

## Identity Matrix:

AI=A, I is the identity matrix.

Source: https://docs.scipy.org/doc/numpy/reference/generated/numpy.identity.html

In [146]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [148]:
np.eye(1)

array([[1.]])

In [149]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [151]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

# Ok, so even np.eye() works for identity matrices

# Matrix Inverse:

# Say, Ax = b

# A<sup>-1</sup>Ax = A<sup>-1</sup>b

# Ix = A<sup>-1</sup>b

# x = A<sup>-1</sup>b

## We already went through an example like this above, the part where it talked about a more intuitive approach.

# Of course, if the matrix of A evalutes to 0, A<sup>-1</sup> will not exist.

### We need to talk to someone about the following part:

<img src="https://cdn.mathpix.com/snip/images/7dYh0vCJD2RfAqJzCB-No5CKJgTc20c8-vtD9Q2CZJc.original.fullsize.png">

# Linear Dependence and Span:

# Slight digression, the left and right inverse of a square matrix are the same.

In [154]:
A = np.random.random((3,3))

In [155]:
A

array([[0.82374101, 0.05037698, 0.73058463],
       [0.17874641, 0.62510461, 0.94277972],
       [0.39591009, 0.25244437, 0.82860616]])

In [156]:
np.linalg.inv(A)

array([[ 2.97458558,  1.51604628, -4.34764352],
       [ 2.39212877,  4.17885377, -6.86380499],
       [-2.1500539 , -1.99750645,  5.37529785]])

In [157]:
A = np.random.random((2,3))

In [158]:
np.linalg.inv(A)

LinAlgError: Last 2 dimensions of the array must be square

In [159]:
B = inv(A)

NameError: name 'inv' is not defined

# we'll come back to this if ever needed

# The Ax = b, equation can:

1. Have no solutions
2. Have one solution
3. Have infinite solutions
#### There are no cases where there are more than one but less than infinite solutions of the equation given above.

<img src="https://cdn.mathpix.com/snip/images/e9ecbG6YzeYhhurszJw8wm9KY_e_q9ytVltlNy3WG-w.original.fullsize.png">

Source : https://www.mathsisfun.com/algebra/systems-linear-equations-matrices.html<br>
https://stackoverflow.com/questions/13626132/how-to-write-summation-expression-in-html

In [171]:
A = np.array([[1,1,1],[0,2,5],[2,5,-11]])

In [172]:
b = np.array([6,-4,27])

In [173]:
x = np.dot(np.linalg.inv(A),b)

In [174]:
x

array([ 6.46341463,  0.56097561, -1.02439024])

In [175]:
np.dot(A,x) - b

array([8.8817842e-16, 0.0000000e+00, 0.0000000e+00])

# The above is close enough to be read as 0.

### Based on the above, let's look at what happened, based on <br>Ax = &Sum;<sub>i</sub>x<sub>i</sub>A<sub>;,i</sub> :

A is:<br>
     [1 1 1]<br>
     [0 2 5]<br>
     [2 5 -11]<br>

x is:<br>
[p]<br>
[q]<br>
[r]<br>

b is:<br>
[6]<br>
[-4]<br>
[27]<br>

therefore:<br> This form is the linear combination:<br>
p + q + r = 6<br>
2q + 5r = -4<br>
2p + 5q -11r = 27<br>

For more explanation, take a look here (same as above): https://www.mathsisfun.com/algebra/systems-linear-equations-matrices.html

# 3 equations, 3 variables, looks solvable and we did solve it above.

# Span: Is the set of all points obtainable by linear combination of the original vectors

Linear independence: Set of vectors is linearly independent if no vector in the set is a linear combination of the other vectors.

# Basically, linear indepedence means the values SHOULD NOT look like this:

In [177]:
A = np.array([[1,2],[2,4]])

In [178]:
print(A)

[[1 2]
 [2 4]]


# The second row is a multiple of the first, so this is not linearly independent